TrainingSystem/TrainingSystem/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('booking.urls')),
]

TrainingSystem/booking/urls.py
from django.urls import path
from . import views
from .views import courses, book, addCourse, addProgram, viewCourse, approveBooking, deleteBooking, completeCourse, rejectBooking
urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.home, name='home'),
    path('course/<int:pk>/', courses.as_view(), name='course'),
    path('book/course/<int:pk>/', book.as_view(), name='book'),
    path('view/course/<int:pk>/', viewCourse.as_view(), name='viewCourse'),
    path('add/course/', addCourse.as_view(), name='addCourse' ),
    path('add/program/', addProgram.as_view(), name='addProgram'),
    path('approve/booking/<int:pk>/', approveBooking.as_view(), name='approve'),
    path('delete/booking/<int:pk>/', deleteBooking.as_view(), name='deleteBooking'),
    path('complete/course/<int:pk>/', completeCourse.as_view(), name='courseComplete'),
    path('insights', views.insights, name='insights'),
    path('reject/booking/<int:pk>/', rejectBooking.as_view(), name='rejectBooking'),
    

]

TrainingSystem/booking/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

class Programs(models.Model):
    name = models.CharField(max_length=200)
    isActive = models.BooleanField(blank=True)

    def __str__(self):
        if self.isActive == True:
            return f'{self.name} is active'
        else:
            return f'{self.name} is not active'


class Course(models.Model):
    staff=(
        ('CAL', 'CALUM'),
        ('YAN', 'YANNA'),
        ('HAN', 'HANNA'),
        ('EXT', 'EXTERNAL'),
    )
    divisions = (
        ('GLO','Company Wide'),
        ('OPE','Operations'),
        ('TEC','Technology'),
        ('FIN','Finance'),
        ('MAR','Marketing'),
    )
    courseNumber = models.IntegerField()
    courseName = models.CharField(max_length=200)
    courseDesc = models.CharField(max_length=500)
    host = models.CharField(max_length=3, choices=staff)
    min_participants = models.IntegerField()
    max_participants = models.IntegerField()
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    program = models.ForeignKey(Programs, on_delete=models.CASCADE, default=4)
    division_access = models.CharField(max_length=3, choices=divisions, default='GLO')
    image=models.ImageField(default='course.jpg',upload_to='course_photos') #Setting the users profile pic
    course_completed = models.BooleanField(blank=True)
    

    def __str__(self):
        return f'{self.courseName} is being delivered by {self.host} on {self.start_date}'

    def get_approved_bookings(self):
        return self.attendees_set.filter(status='APR')

class attendees(models.Model):
    courseNeededBy = [
        ('W1M', 'Within 1 Month'),
        ('1-3', '1-3 Months'),
        ('3-6', '3-6 Months'),
        ('6+M', '6+ Months'),
    ]
    statuses = [
        ('PEN', 'Pending'),
        ('APR', 'Approved'),
        ('REJ', 'Rejected'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    role = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    course_due = models.CharField(max_length=3, choices=courseNeededBy)
    your_development = models.CharField(max_length=3000)
    status = models.CharField(max_length=3, choices=statuses, default='PEN')


    def __str__(self):
        return f'{self.user} has booked onto {self.course}'

TrainingSystem/booking/forms.py
from django.db.models import fields
from django import forms
from django.forms import widgets
from .models import Course, Programs, attendees

staff=[
        ('CAL', 'CALUM'),
        ('YAN', 'YANNA'),
        ('HAN', 'HANNA'),
        ('EXT', 'EXTERNAL'),
]
class addCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'
   
    courseName = forms.CharField(required=True)
    courseDesc = forms.CharField(required=True, widget=forms.Textarea)
    host = forms.ChoiceField(choices=staff, required=True)
    min_participants = forms.IntegerField(required=True)
    max_participants = forms.IntegerField(required=True)
    start_date = forms.DateTimeField(required=True, input_formats=[ '%d/%m/%Y %H:%M'])
    end_date = forms.DateTimeField(required=True, input_formats=[ '%d/%m/%Y %H:%M'])

class addprogramForm(forms.ModelForm):
    class Meta:
        model = Programs
        fields = '__all__'

class bookCourse(forms.ModelForm):
    class Meta:
        model = attendees
        fields = [ 'role', 'course_due', 'your_development']
        labels = {
            'your_development':'How has this training been identified? How will you apply the learning in your role? How will you measure the success of this learning?',
            'role':'Your Job Title'
        }
        widgets = {
            'your_development': widgets.Textarea()
        }

    
    

TrainingSystem/booking/views.py
from users.models import Profile
from django import urls
from django.db.models import manager
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import DeleteView
from .models import attendees, Course, Programs
from django.views.generic.detail import DetailView
from django.views.generic import View, CreateView, FormView
from .forms import addCourseForm, addprogramForm, bookCourse
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.conf import settings
import pandas as pd

def dashboard(request):
    #Getting the database objects
    attendents = attendees.objects.all()
    courses = Course.objects.all()
    programs = Programs.objects.all()
    userData = User.objects.all()

    #Counting the number of bookings there are per program
    attDict = {}
    for p in programs:
        p_count = p.course_set.all()
        for ll in p_count:
            ll_count = ll.attendees_set.filter(status='APR')
            counting = ll_count.count()
            attDict[p.name] = counting
    print(attDict)

    #Need all this for the user data table
    UserDetails ={} #Setting a dict to create a DataFrame from 
    for u in userData: #Looping through the user object
        testlist = [] #Starting empty list
        userID = u.id #Getting the user ID
        testlist.append(userID) #Appending the list with the ID
        UserDetails[userID] = userID #Adding the user ID to the dict as a key and value

        userName = u.username
        testlist.append(userName)
        UserDetails[userID] = testlist #Adding the username to dict as a value with the user ID as a key

        userEmail = u.email
        testlist.append(userEmail)
        UserDetails[userID]= testlist

        userDepartment = u.profile.get_department_display
        testlist.append(userDepartment)
        UserDetails[userID] = testlist

        userManager = u.profile.manager #Going through the user profile to get manager, user is a 1 to 1 relationship so I can access attributes by seperating them with .'s
        testlist.append(userManager)
        UserDetails[userID] = testlist

        totalCompleteCourse = u.user.filter(status='APR').filter(course__course_completed=True).count() #Creating a query on the user object to count the number of courses completed, this is a 1 to many relationship through forign key so to access those atributes in a queryset use x__y
        testlist.append(totalCompleteCourse)
        UserDetails[userID] = testlist

        completedCourses = u.user.filter(status='APR').filter(course__course_completed=True).values_list('course__courseName', flat=True) #Same as above query but this time i use .values_list to only get the values of the queryset which in this case is the courseName
        completedList = list(completedCourses)#Turning the queryset into a list
        testlist.append(completedList)
        UserDetails[userID] = testlist
    
    df = pd.DataFrame.from_dict(UserDetails, orient='index', columns=['EmployeeNumber','Name', 'Email','Department','Manager','TotalCoursesCompleted', 'CoursesCompleted']) #Creating 1 DataFrame from the dict
    allData=[] #This list will be passed to the HTML template
    for i in range(df.shape[0]): #For loop to get data from DF but keep column structure 
        temp = df.iloc[i]
        allData.append(dict(temp))
    
    #Needed to get data for chart on Dashboard
    emptDict = {} #New dict to hold approved bookings
    for event in courses: #Looping through the courses object
        attendies =  event.attendees_set.filter(status='APR').count() #Getting attendees through reverse lookup on forign key which is attendees_set.filter() and then counting the values
        emptDict[event.courseName] = attendies

    #print(emptDict)
    #Lists for the chart
    valueList = []
    labels = []
    for key,value in attDict.items():#Getting the keys and values seperate from the dict
        valueList.append(value)
        labels.append(str(key))

    context = {'attendees' : attendents, 'course': courses, 'programs': programs, 'attendants':emptDict, 'valueList':valueList, 'labels':labels, 'userData':userData, 'allData':allData} #Passing data to HTML template 
    return render(request, 'booking/dashboard.html', context) #DONT FORGET TO ADD CONTEXT AS ARGUMENT

def home(request):
    attendents = attendees.objects.all()
    courses = Course.objects.all()
    TEC_courses = Course.objects.filter(division_access="TEC")
    OPE_courses = Course.objects.filter(division_access="OPE")
    FIN_courses = Course.objects.filter(division_access="FIN")
    MAR_courses = Course.objects.filter(division_access="MAR")
    GLO_courses = Course.objects.filter(division_access="GLO")
    context = {'attendees' : attendents, 'course': courses, 'TEC_courses':TEC_courses, 'OPE_courses':OPE_courses, 'FIN_courses':FIN_courses, 'MAR_courses':MAR_courses, 'GLO_courses':GLO_courses}
    search_input = request.GET.get('search-area') or '' #Getting the value of the searchbar from HTML template
    if search_input: #If there is a value in there
        context['course'] = context['course'].filter(courseName__icontains=search_input) #Creating a queryset which filters the course object so if it contains the value in search bar it will appear, that is icontains
    return render(request, 'booking/home.html', context)

class courses(DetailView): #Using Django generic detail view, this handles lots of things, allows user to see details about a model eg. course
    model = Course
    template_name = 'booking/courses.html'

    def get_queryset(self):
        return Course.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(courses, self).get_context_data(**kwargs)
        context['attendees'] = attendees.objects.filter(course = self.object) #Getting a list of attendees that are related to the course instance
        return context

class book(View): #Creating my own view to have better control over what is happening
    def get(self, request, *args, **kwargs): #This function specifies what happens when the page is loaded
        course_id = self.kwargs.get('pk', None) #Getting the course ID from the URL, the number in URL is called pk
        course = Course.objects.filter(id = course_id) #Creating a queryset and filtering it by the ID got above
        form = bookCourse() #Loading the custom form from forms.py
        attendents = attendees.objects.filter(id = course_id) #Getting list of attendees thatare on the course
        context = {'course': course, 'attendees':attendents, 'form':form}
        return render(request, 'booking/book.html', context)
    
    def post(self, request, *args, **kwargs): #This function specifies what happens when a POST request is sent 
        course_id = self.kwargs.get('pk', None)
        course_inst = Course.objects.get(id = course_id) 
        form = bookCourse(request.POST) #Adding ewquest.POST to capture data sent in the post request
        if form.is_valid():
            data = form.cleaned_data #Getting form data
        if Course.objects.filter(id = course_id).filter(attendees__user=self.request.user).exists(): #Checking to see if the user booking a place has already booked onto that course, doing this by making a queryset to filter the attendees to the current user and if they exist return error
            return HttpResponse('error')
        else:
            attendants = attendees.objects.create(  #Creating an attendants object to be put in database
                user = self.request.user,
                role = data['role'],
                course = course_inst,
                course_due = data['course_due'],
                your_development = data['your_development'],
                )
            email = self.request.user.profile.manager.email #Getting the users manager's email
            url = reverse_lazy('approve', kwargs={'pk':attendants.id}) #Getting the URL for managers to confirm booking place

            send_mail(
                'This is an automatic message', #Subject
                f'Hello {self.request.user.profile.manager}, {self.request.user} has booked onto {course_inst}. Could you please approve or deny their training? To approve please follow this link http://127.0.0.1:8000{url}. ', #Message
                'ilearn112@gmail.com', #From email
                [email], #To email
                
            )
            attendants.save() #DONT FORGET TO SAVE THE OBJECT
            return redirect('home')
    
class viewCourse(View):
    def get(self, request, *args, **kwargs):
        course_id = self.kwargs.get('pk', None)#Getting the course ID from the URL 
        course = Course.objects.filter(id = course_id)#Getting the object that matches that ID
        context = {'course': course}
        return render(request, 'booking/viewCourse.html', context)

class addCourse(CreateView): #Using Django's generic create view, again this handles a lot of things by default like GET & POST functions
    model = Course
    template_name = 'booking/addCourse.html'
    form_class = addCourseForm #Specifying the form to be used from forms.py
    success_url = reverse_lazy('home')

class addProgram(CreateView):
    model = Programs
    template_name = 'booking/addProgram.html'
    form_class = addprogramForm
    success_url = reverse_lazy('home')

class approveBooking(View):
    def get(self, request, *args, **kwargs):
        attend_id = self.kwargs.get('pk', None)
        booking_inst = attendees.objects.get(id = attend_id)
        context = {'bookingInst':booking_inst}
        return render(request,'booking/approveRequest.html', context)
    
    def post(self, request, *args, **kwargs):
        attend_id = self.kwargs.get('pk', None)
        booking_inst = attendees.objects.get(id = attend_id)
        booking_inst.status='APR'

TrainingSystem/booking/templates/booking/addCourse.html
{% extends "booking/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Add Course {% endblock title %}
{% block content %}
<div class="mx-auto" style="width: 700px;">
<br>
<h1>Add a new course</h1>
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button class="btn btn-success" type="submit">Add Course</button>
</form>
</div>

<!--JQuery functions to add a date time picker-->
<script>
    $(function () {
      $("#id_start_date").datetimepicker({
        format: 'd/m/Y H:i',
      });
    });
  </script>

<script>
    $(function () {
      $("#id_end_date").datetimepicker({
        format: 'd/m/Y H:i',
      });
    });
  </script>

{% endblock content %}

TrainingSystem/booking/templates/booking/addProgram.html
{% extends "booking/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Add Course {% endblock title %}
{% block content %}
<div class="mx-auto" style="width: 700px;">
<br>
<h1>Add a new program</h1>
<form method="POST">
    {% csrf_token %}
    {{form|crispy}}
    <br>
    <button class="btn btn-success" type="submit">Add Program</button>
</form>
</div>

{% endblock content %}

TrainingSystem/booking/templates/booking/approveRequest.html
{% extends "booking/base.html" %}
{% block content %}

<br>
<br>
<div class="content-section container px-4">

<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 mx-auto">
    <div class="card rounded-0 p-0 shadow-sm">
      <div style="max-height: 200px; max-width: 400px; overflow: hidden;">
      </div>
      <div class="card-body text-center">
          <h4>Please approve this training request</h4>
          <hr>
          <p><b>Employee: </b>{{bookingInst.user}}</p>
          <p><b>Course: </b>{{bookingInst.course.courseName}}</p>
          <p><b>Delivered by: </b>{{bookingInst.course.host}}</p>
          <p><b>On </b>{{bookingInst.course.start_date}}</p>
          <p><b>To </b>{{bookingInst.course.end_date}}</p>
          <form method="POST">
              {% csrf_token %}
              <button class="btn btn-success">Approve</button>
          </form>
      </div>
    </div>
  </div>
</div>
<div class="colorulDiv" style="height: 100%; width: 100%;">

</div>
{% endblock %}

TrainingSystem/booking/templates/booking/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>{% block title %}{% endblock title %}</title>
  <meta name="description" content="The HTML5 Herald">
  <meta name="author" content="SitePoint">

   <!--Bootstrap CSS-->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

   <!--Font Awesome-->
   <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
   <!-- jQuery -->
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

   <!-- XDSoft DateTimePicker -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
   <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

   <!--Chart jS-->
   <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.3.2/chart.min.js"></script>

   <!--DataTables CSS + JS-->
   <link href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
   <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
  
   <link type="text/css" href="{% static 'booking/main.css' %}">
   <script src="{% static 'booking/charts.js' %}"></script>
  
</head>

<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">I-Learn</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              {% if request.user.is_staff %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'addCourse' %}">Add Courses</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'addProgram' %}">Add Programs</a>
              </li>
              {% endif %}
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'profile' %}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
              </li>
              
              {% else %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login' %}">Login</a>
              </li>
              {% endif %}
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search Courses" aria-label="Search" name="search-area" value="{{search_input}}">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script></body>
</html>

TrainingSystem/booking/templates/booking/book.html
{% extends "booking/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Book Training {% endblock title %}
{% block content %}

<!--STYLES FOR POPUP-->

<style>
  /* The Modal (background) */
  .modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
  }

  /* Modal Content/Box */
  .modal-content {
    background-color: #fefefe;
    margin: 15% auto; /* 15% from the top and centered */
    padding: 20px;
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
  }

  /* The Close Button */
  .close {
    color: #aaa;
    float: right;
    font-size: 28px;
    font-weight: bold;
  }

  .close:hover,
  .close:focus {
    color: black;
    text-decoration: none;
    cursor: pointer;
  }
</style>

<br>
<div class="container px-4">
    {% for c in course %}
    <h1>{{c.courseName}}</h1>
    <div class="row gx-5">
      <div class="col">
       <div class="p-3 border bg-light">
           <b>Course: </b><p>{{c.courseName}}</p>
           <b>Description</b><p>{{c.courseDesc}}</p>
           <b>Trainer: </b><p>{{c.host}}</p>
           <b>Start Date: </b><p>{{c.start_date}}</p>
           <b>End Date: </b><p>{{c.end_date}}</p>
           {% if c.attendees_set.count > c.max_participants %}
           <a class="btn btn-secondary"disabled>Sorry this course is fully booked</a>
           {% else %}
           <button id="myBtn" class="btn btn-success">Book a place</button>
            <div id="myModal" class="modal">
              <!-- Popup content -->
              <div class="modal-content">
                <span class="close">&times;</span>
                <h2>Booking form</h2>
                  <form method="POST">
                    {% csrf_token %}
                    {{form| crispy}}
                    <br>
                    <button class="btn btn-success" type="submit">Go</button>
                  </form> 
              </div>
            </div>
           {% endif %}
           {% if request.method == POST %}
            <script>
              alert('{{message}}');
            </script>
           {% endif %}
        </div>
      </div>
    {% endfor %}
    </div>
  </div>

  <!--SCRIPT FOR POPUP-->
  <script>
    // Get the modal
    var modal = document.getElementById("myModal");

    // Get the button that opens the modal
    var btn = document.getElementById("myBtn");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close")[0];

    // When the user clicks on the button, open the modal
    btn.onclick = function() {
    modal.style.display = "block";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
    modal.style.display = "none";
    }

    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
    }
  </script>
  
{% endblock content %}

TrainingSystem/booking/templates/booking/complete.html
{% extends "booking/base.html" %}
{% block content %}

<br>
<br>
<div class="content-section container px-4">

<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 mx-auto">
    <div class="card rounded-0 p-0 shadow-sm">
      <div style="max-height: 200px; max-width: 400px; overflow: hidden;">
      </div>
      <div class="card-body text-center">
          <h4>This course is now marked as complete!</h4>
        <a href="{% url 'dashboard' %}" class="btn btn-primary"></i> Dashboard</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

TrainingSystem/booking/templates/booking/courses.html
{% extends "booking/base.html" %}
{% block title %} Courses {% endblock title %}
{% block content %}

<!--Using database data in the {brackets} -->

<div class="container px-4">
    <h1>{{course.courseName}}</h1><!--Displaying course name, first I reference the object course and then display an attribute which is .courseName -->
    <h2>Delivered by: {{course.host}}</h2><!--Displaying the course host -->
    <div class="row gx-5">
      <div class="col">
        <div class="p-3 border bg-light"><b>attendees:</b></div>
        {% for a in attendees %}<!--Using a for loop to display single objects not a queryset -->
       <div class="p-3 border bg-light">{{a.user}}</div><!--Listing all particients -->
       {% endfor %}
      </div>
    </div>
</div>
{% endblock content %}

TrainingSystem/booking/templates/booking/deleteBooking.html
{% extends "booking/base.html" %}
{% block content %}

<br>
<br>
<div class="content-section container px-4">

<div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 mx-auto">
    <div class="card rounded-0 p-0 shadow-sm">
      <div style="max-height: 200px; max-width: 400px; overflow: hidden;">
      </div>
      <div class="card-body text-center">
        <a href="{% url 'dashboard' %}" style="text-decoration: none; color: black;"><i class="fas fa-arrow-circle-left" style="color: black;"></i> Dashboard</a>
        <form method="POST">
            {% csrf_token %}
            <p>Are you sure you want to delete this task?</p>
            <input class="btn btn-danger" type="submit" value="Delete">
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

TrainingSystem/booking/templates/booking/rejectBooking.html
{% extends "booking/base.html" %}
{% block content %}

<br>
<br>
<div class="content-section container px-4">

<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6 mx-auto">
    <div class="card rounded-0 p-0 shadow-sm">
      <div style="max-height: 200px; max-width: 400px; overflow: hidden;">
      </div>
      <div class="card-body text-center">
          <h4>Are you sure you want to reject {{bookingInst.user}}'s request?</h4>
          <hr>
          <form method="POST">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Yes I am sure</button>
          </form>
      </div>
    </div>
  </div>
</div>
<div class="colorulDiv" style="height: 100%; width: 100%;">

</div>
{% endblock %}